name: Deploy React JS with Docker

on:
  workflow_dispatch:
env:
  NODE_VERSION: "20.x"
  FOLDER: ~/autogo/front
  IMAGE: autogo-front
  IMAGE_VERSION: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ./app

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create folder to VPS
        run: |
          mkdir -p ${{ env.FOLDER }}

      - name: Copy application files to VPS
        run: |
          scp -o StrictHostKeyChecking=no -r -p ./app/* ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ env.FOLDER }}/

      - name: Ensure compose.yaml exists
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd ~/app
          if [ ! -f compose.yaml ]; then
            echo "Error: compose.yaml not found!"
            exit 1
          fi
          EOF

      # - name: copy .env file
      #   run: |
      #     ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
      #     cd ~/app
      #     r

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd ${{ env.FOLDER }}
          docker compose down
          docker compose up -d --build
          EOF
